### PR TITLE
Update Socks.pm

### PR DESCRIPTION
**Pull request by kostya-ten**
no warnings;

### CODE REVIEW

**Comment by olegwtf** [comment]
I don't like it. This will not fix cause of the warning. With the same success you can stop using `-w` option.

**Comment by kostya-ten** [comment]
Mojo uses by default -w
https://metacpan.org/pod/Mojo::Base

**Comment by olegwtf** [comment]
Where you can see this?

**Comment by olegwtf** [comment]
`perl -MMojo::Base -MIO::Socket::Socks -E 1`
I can't see warnings

**Pull request closed without merging**
